apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-service-database
  namespace: dt-bank
spec:
  serviceName: account-service-database
  replicas: 1
  selector:
    matchLabels:
      app: account-service-database
  template:
    metadata:
      labels:
        app: account-service-database
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - name: account-svc-db
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "test"
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db-credentials, key: POSTGRES_PASSWORD } }
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe: # K8s equivalent of healthcheck
            exec:
              command: [ "pg_isready", "-U", "test", "-d", "test" ]
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
