application:
  config:
    gateway:
      url: "http://host.docker.internal"
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-service.dt-bank.svc.cluster.local:8080/eureka/"
management:
  zipkin:
    tracing:
      endpoint: "http://zipkin.dt-bank.svc.cluster.local:9411/api/v2/spans"
spring:
  data:
    redis:
      host: "redis.dt-bank.svc.cluster.local"
  rabbitmq:
    host: "rabbitmq.dt-bank.svc.cluster.local"
  flyway:
    user: "test"
    password: "test"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak.keycloak.svc.cluster.local:8080/realms/dt-bank"
